#!/usr/bin/env bash

clear
# if [ $1 = "gcc" ]; then
#     echo "Compiler: gcc"
#     export CXX=/usr/bin/g++
# elif [ $1 = "clang" ]; then
#     echo "Compiler: clang"
#     export CXX=/usr/bin/clang++
# fi

build_type=$1

cmake -S . -B "${build_type}" -DCMAKE_BUILD_TYPE=${build_type}
cmake --build "${build_type}"
